Hylozoic/hylo-node

api/models/Network.js
api/models/Post.js
api/policies/checkAndSetMembership.js
api/policies/checkAndSetPost.js
api/policies/inNetwork.js
test/setup.js
test/unit/controllers/CommunityController.test.js
test/unit/models/Post.test.js

Allow viewing content from other communities in network

Network access

---

api/models/Comment.js
api/models/Device.js
api/models/PushNotification.js

Please take a look. I passed options (which is currently just {transacting: trx}) through everything.

pass transaction through sendPushNotification methods

---

README.md

There was a discrepancy about 1337 vs. 3001.

Fix a typo about a port.

---

api/policies/renderOpenGraphTags.js
views/openGraphTags.ejs

sorry about the standardization noise

Social sharing

---

.gitignore
README.md

documenting roadblocks for beginners

---

api/controllers/PostController.js
api/models/Media.js
api/policies/renderOpenGraphTags.js
api/services/GetImageSize.js
migrations/20151118120532_drop-project-urls.js
migrations/schema.sql
package.json
test/unit/controllers/PostController.test.js
test/unit/controllers/ProjectController.test.js
test/unit/services/GetImageSize.test.js
views/openGraphTags.ejs

This should not be merged until https://github.com/Hylozoic/hylo-node/pull/57 has been merged, and the database updated

Projects use media for images and og tags display width and height

---

api/controllers/DeviceController.js
api/models/Device.js
api/models/PushNotification.js
api/services/OneSignal.js
migrations/20160131201706_add_version_to_devices.js
migrations/schema.sql
package.json

@levity Merging this is time sensitive, so don't merge it please. But let me know if it's good to go.
Thanks

(DON'T MERGE YET) OneSignal integration

---

api/controllers/MobileAppController.js
config/policies.js
config/routes.js

@levity Adding a route for the mobile apps to get info about whether they should force update.
Figured I'd make a new controller for it. Let me know if you want this somewhere else.

Add auto-update-info route

---

api/controllers/CommunityController.js

Continues from https://github.com/Hylozoic/hylo-node/pull/89
Will be (much) easier to read once that's merged. (which will be once this is merged: https://github.com/Hylozoic/hylo-frontend/pull/100)

Active community 3

---

migrations/schema.sql
test/unit/controllers/CommentController.test.js
test/unit/controllers/DeviceController.test.js
test/unit/controllers/NetworkController.test.js
test/unit/controllers/PostController.test.js
test/unit/controllers/ProjectController.test.js
test/unit/models/Comment.test.js
test/unit/models/Membership.test.js
test/unit/models/Organization.test.js
test/unit/models/Post.test.js
test/unit/models/Skill.test.js
test/unit/policies/checkAndSetPost.test.js

the schema didn't get updated with this migration https://github.com/Hylozoic/hylo-node/commit/fdf4dd326b2c4dadbf063d7fc976056eab3d3978, 
this is the update, along with test fixes

Fix schema

---

api/controllers/MobileAppController.js

DON'T MERGE YET
this is to be merged once iOS app v1.7 is in the app store

Force ios update

---

api/controllers/CommentController.js
api/controllers/PostController.js
api/models/Community.js
api/models/Tag.js
api/services/Email.js
api/services/Frontend.js
api/services/RichText.js
lib/community/digest.js
lib/community/digest2/formatData.js
lib/community/digest2/index.js
lib/community/digest2/personalizeData.js
lib/community/digest2/sampleData.json
lib/community/digest2/util.js
package.json
test/setup/factories.js
test/setup/helpers.js
test/unit/models/Notification.test.js
test/unit/services/RichText.test.js
test/unit/services/digest2.test.js

less coupling, ~200 fewer LOC, more tests 🎉

New digest

---

api/controllers/LinkPreviewController.js
api/models/LinkPreview.js
api/services/Queue.js
config/policies.js
config/routes.js
migrations/20160708165233_link-previews.js
migrations/schema.sql
test/setup/helpers.js
test/unit/models/LinkPreview.test.js
test/unit/models/Post.test.js

Link previews

---

api/controllers/SessionController.js
api/controllers/UserController.js
api/services/Analytics.js

Goes with https://github.com/Hylozoic/hylo-redux/pull/92

Track signup events

---

api/controllers/CommentController.js
api/controllers/PostController.js
api/policies/checkAndDecodeToken.js
api/services/Email.js
api/services/Frontend.js
config/policies.js
config/routes.js
lib/community/digest2/index.js
lib/community/digest2/personalizeData.js
test/unit/controllers/CommentController.test.js
test/unit/controllers/PostController.test.js
test/unit/policies/checkAndDecodeToken.test.js
test/unit/services/digest2.test.js

This goes with the new Digest template created by Derek, (see the 'Simpler' version in SendWithUs).
I also need to add something in hylo-redux on the communities page for displaying a notification in the query string. (see line 214 of CommentController.js).
But nothing breaks if that's missing and I wanted to get this in first.

Digest update

---

api/graphql/models.js

Normally wouldn't put something like this in a PR, but want @levity to look at everything graphql related for awhile to make sure I'm on the right track/not missing something

add slug to graphql

---

api/controllers/SearchController.js

Related to Complete Request fix: https://github.com/Hylozoic/hylo-redux/pull/227

Searches can take an array of community IDs

---

.gitignore
api/controllers/PostController.js
api/services/TagPresenter.js
test/unit/controllers/PostController.test.js

Remove event from being a special tag

---

lib/migration.js

@levity this should be it, but I'm still getting set up to run it on my comp, just wanted to get you to look at it

ensure old project requests get maintained as such

---

api/models/Community.js

Adresses this:
https://trello.com/c/hUQZpBKu
together with this: https://github.com/Hylozoic/hylo-redux/pull/282

Only return active moderators

---

api/controllers/TagController.js

this is necessary for https://github.com/Hylozoic/hylo-redux/pull/283

tag creator response should return at least the id

---

README.md

Updates based on a fresh install on Linux. Sanitised version of the current .env file, rearranged the database stuff a little including creating the test db.

Update to reflect current process

---

api/policies/inSameCommunityOrNetwork.js

I think there will also be a tiny front-end tweak, to make it so that the 'message' bubble doesn't appear for axolotl on its profile... 
we'll save that for when it becomes an intelligent AI super-axolotl

use an env var to allow access to axolotls profile

---

README.md
api/graphql/makeModels.js
api/graphql/schema.graphql

Merging without tests to enable other branches to be created! 
Stops creator in graphql responses for posts and comments from being null.

Add comments to graphql

---

api/graphql/makeModels.js
api/graphql/schema.graphql

Add bannerUrl to Person GraphQL

---

api/graphql/makeModels.js
api/graphql/schema.graphql

Adds location, bio, twitter_name, facebook_url, linkedin_url, url, location as possible GraphQL responses. Added to enable MemberProfile page.

More Person details in GraphQL response

---

api/controllers/PostController.js
api/graphql/index.js
api/graphql/mutations.js
api/graphql/schema.graphql
api/models/post/util.js
test/unit/models/post/util.test.js

tests pass, and I also verified that it works as expected from hylo-redux still, the start a thread functionality
a query looks like: 
```
mutation {
findOrCreateThread(data: {participantIds: ["2"]}) {
id
participants {
id
name
}
}
}
```

find or create thread graphql + refactor

---

api/graphql/makeModels.js
api/graphql/schema.graphql

Saves having to muck about with integer constants in the front end.

Add an explicit moderator flag to gql

---

api/graphql/index.js
api/graphql/makeModels.js
api/graphql/schema.graphql
lib/graphql-bookshelf-bridge/fetcher.js
lib/graphql-bookshelf-bridge/makeResolvers.js

@levity you'll need this if you're working off post-details branch on evo

Post details gcl

---

api/graphql/schema.graphql

Needed to sort/limit request for 'Recent Activity' view.

Enable vars on comment requests

---

api/graphql/makeModels.js
api/graphql/schema.graphql
api/models/User.js

Required for the 'Upvotes' tab on MemberProfile. Please check I have the right nonadminFilter? :)

Add votes to graphql

---

api/graphql/filters.js
api/graphql/index.js
api/graphql/makeModels.js
api/graphql/schema.graphql
api/graphql/searchQuerySet.js
api/services/Search.js
api/services/Search/forPosts.js
api/services/Search/forUsers.js
lib/graphql-bookshelf-bridge/fetcher.js
lib/graphql-bookshelf-bridge/index.js
lib/graphql-bookshelf-bridge/makeResolvers.js
lib/graphql-bookshelf-bridge/util/applyPagination.js
lib/graphql-bookshelf-bridge/util/initDataLoaders.js
test/api/graphql/filters.test.js
test/api/graphql/index.test.js
test/api/graphql/searchQuerySet.test.js
test/index.js
test/unit/services/Search.test.js

sketch out a way of adding root endpoints that return query sets to the
graphql api, while delegating their implementation into makeModels
all existing tests pass, but this hasn't been itself tested -- i'm just offering it for discussion

fetchMany in graphql schema

---

api/graphql/makeModels.js
api/graphql/schema.graphql
api/graphql/searchQuerySet.js
api/models/User.js
lib/graphql-bookshelf-bridge/fetcher.js
lib/graphql-bookshelf-bridge/util/index.js
lib/graphql-bookshelf-bridge/util/initDataLoaders.js
lib/graphql-bookshelf-bridge/util/presentQuerySet.js
test/api/graphql/loaders.test.js

@levity here's the graphql mystery

(wip) Subscribed topics

---

api/graphql/makeModels.js
api/graphql/schema.graphql
api/graphql/searchQuerySet.js
api/graphql/searchQuerySet.test.js

topic must be specified by its ID

add filtering by topic to graphql post search

---

api/graphql/index.js
api/graphql/mutations.js
api/graphql/schema.graphql

https://trello.com/c/hwM9nVeA/362-api-enable-subscribing-unsubscribing-for-a-topic-within-a-community

graphql topic sub/unsub

---

package.json
yarn.lock

I need this to complete HyloEditor work... See related [updates in hylo-utils](https://github.com/Hylozoic/hylo-utils/commit/d0ebdc7173478c14438f982ff1df1189f7b856bc)

hylo-utils bump: adding to whitelisted attributes in sanitization

---

api/graphql/index.js
api/graphql/mutations.js
api/graphql/schema.graphql

Allow activities to be marked as read through graphql

Mark as read

---

api/graphql/index.js
api/graphql/makeModels.js
api/graphql/mutations.js
api/graphql/schema.graphql
api/graphql/searchQuerySet.js
api/graphql/searchQuerySet.test.js
api/models/CommunityTag.js
api/services/Search.js

put newPostCount and isSubscribed on CommunityTopic instead
also remove Search.forCommunityTopics and use the new relation
filtering option

remove TopicSubscription from schema

---

api/controllers/CommunityController.js
api/controllers/TagController.js
api/graphql/filters.js
api/graphql/makeModels.js
api/graphql/mutations.js
api/graphql/schema.graphql
api/models/CommunityTag.js
api/models/Invitation.js
api/models/Post.js
api/models/Tag.js
api/models/TagFollow.js
api/models/User.js
api/models/post/createPost.js
migrations/20170531132953_add-followers-to-communties_tags.js
migrations/20170605161512_rename-followers.js
migrations/schema.sql
test/unit/models/TagFollow.test.js

There are a couple of changes to the live database that will go with this one. Specifically in CommuntiyTags, setting updated_at and created_at when they're not currently set, and running consolidateFollowerCount on all Community Tags.

See all topics

---

api/models/post/createPost.js

Part #2 of this ticket: https://trello.com/c/QV9zPrCy/410-making-a-new-post-bumps-ones-own-newpostcount

Don't bump new post count for creator of post

---

api/controllers/PostController.js
api/models/Notification.js
api/services/Queue.js
api/services/Websockets.js
config/policies.js
config/routes.js

This:
- provides for socket.io updates from the worker process
- updates the user socket with new notifications
Let me know if there's a better way to construct the object from Bookshelf, it feels a little klunky.

Notifications socket updates

---

api/graphql/index.js
api/graphql/makeModels.js
api/graphql/schema.graphql

https://trello.com/c/0Nzpxkfx/445-opening-the-notifications-dropdown-doesnt-remove-its-badge

moves notifications graphQL out of ME and into root

---

api/models/Notification.js
api/services/Queue.js

Let's see if this helps the Redis explosion!

Explicitly lower Sails after socket update

---

api/graphql/mutations.js
api/graphql/schema.graphql

goes with https://github.com/Hylozoic/hylo-evo/pull/142

rename generic `id` to `communityId`

---

api/controllers/LinkPreviewController.js
api/graphql/index.js
api/graphql/makeModels.js
api/graphql/mutations.js
api/graphql/schema.graphql
api/models/linkPreview/findOrCreateByUrl.js
api/models/post/setupPostAttrs.js
lib/graphql-bookshelf-bridge/makeResolvers.js
lib/graphql-bookshelf-bridge/makeResolvers.test.js

To be released with: https://github.com/Hylozoic/hylo-evo/pull/135

graphql for LinkPreview

---

api/graphql/makeModels.js
api/graphql/schema.graphql
api/services/Search/forUsers.js

Based upon network-communities branch in https://github.com/Hylozoic/hylo-node/pull/308

Network members search

---

api/graphql/makeModels.js
api/graphql/schema.graphql

This is ready for review. However, there are some changes that need to be made to hylo-evo before this can be merged.
- these changes are now on master. Here's the PR:
https://github.com/Hylozoic/hylo-evo/pull/170

User Profile MBL-8

---

api/graphql/makeModels.js
api/graphql/schema.graphql
api/models/Post.js
lib/graphql-bookshelf-bridge/makeResolvers.js
migrations/20170911145855_media-position.js

and document the use of the `arguments` option in relations

WEB-61: Post images

---

api/graphql/schema.graphql

This must be deployed alongside Hylozoic/hylo-evo#237

remove snake case from graphql schema

---

migrations/20171116104134_add-pinned_at-to-communities_posts.js
migrations/schema.sql

I need to make this change to the production database ahead of the main changes for this issue, so I can do a migration:
```UPDATE communities_posts SET pinned_at = now() WHERE pinned = true;```

add pinned_at to communities_posts

---

api/graphql/makeModels.js
api/graphql/schema.graphql

Exposes `isAdmin` on the current user. I couldn't think of a sensible way to test this (short of testing all of  `makeModels`!), let me know if you have any bright ideas in that department.

Web 330/is admin

---

api/graphql/index.js
api/graphql/makeModels.js
api/graphql/schema.graphql

Forgot one! Need this to do a communities drop-down/autocomplete.

WEB-330: autocomplete communities

---

api/models/FlaggedItem.js
api/models/flaggedItem/notifyUtils.js
test/unit/models/flaggedItem/notifyUtils.test.js

Also requires a change to production environment variables, adding HYLO_ADMINS

Illegal content notice dev 13

---

api/controllers/PostController.js
api/graphql/makeModels.js
api/graphql/schema.graphql
api/models/Tag.js
api/models/comment/createComment.js
api/models/post/createPost.js
api/models/post/updatePost.js
test/unit/controllers/PostController.test.js
test/unit/models/Post.test.js
test/unit/models/Tag.test.js

Not to be merged until frontend and mobile work is ready to go live

(DONT MERGE YET) Update backend for topic line in post editor WEB-365

---

api/controllers/MobileAppController.js
test/unit/controllers/MobileAppController.test.js

When merging this be sure to add MINIMUM_SUPPORTED_MOBILE_VERSION to heroku env variables set to the latest mobile version

check update for mobile uses env variable DEV-301

---

api/graphql/schema.graphql

@lorenjohnson you're gonna love this ;)
Small change to the graphql schema to keep the queries the same between hylo and holo.
An alternative would be to split out the queries in the frontend, but for this first pass I wanted to keep it simple.

Holo Merge

---

api/graphql/makeModels.js
api/graphql/schema.graphql
api/models/User.js

required by https://github.com/Hylozoic/hylo-evo/pull/359

Dev-407 Network Moderators

---

api/graphql/index.js
api/graphql/mutations/index.js
api/graphql/mutations/post.js
api/graphql/schema.graphql
api/models/Post.js
api/models/post/fulfillPost.js

[Completes #464 ]
Allows user to fulfill or unfulfill a post.
Fulfill sets fulfilledAt to date, unfulfill sets fulfilledAt back to null

464 track post fulfilled

---

api/controllers/SessionController.js
api/controllers/UserController.js
api/models/Invitation.js

Fixes https://github.com/Hylozoic/hylo-node/issues/481

Fix forgot password feature not working

---

api/controllers/PostController.js
api/models/Community.js
api/models/Post.js
api/models/post/migration.js
api/models/post/updatePost.js
api/models/post/validatePostData.js
api/services/Search/util.js
api/services/Search/util.test.js
lib/community/digest2/formatData.js
lib/community/digest2/personalizeData.js
lib/community/digest2/util.js
test/unit/services/Search.test.js

467-resources

---

api/graphql/makeModels.js
api/graphql/mutations/post.js
api/graphql/schema.graphql
api/models/Community.js
api/models/Post.js
api/models/User.js
api/models/post/createPost.js
api/models/post/setupPostAttrs.js
migrations/20200528144015_rename-locations-text-for-mobile.js

and location relationships become locationObject

Temp fix for mobile locationText goes back to location

---

api/models/Comment.js

Optional, but recommended for: https://github.com/Hylozoic/hylo-evo/issues/441

Add community ID to comment activity generation

---

api/graphql/makeModels.js
api/graphql/schema.graphql
api/services/Search/forUsers.js
api/services/Search/util.js

So we can show members on the map

Allow for searching users by bounding box

---

api/graphql/makeModels.js
api/models/post/setupPostAttrs.js
package.json
yarn.lock

Closes #501 
Add [he](https://www.npmjs.com/package/he) for HTML entity encoding/decoding
In the example from the issue, `Communities <=> Food <=> The Land <=> Tech` is saved in the database as `Communities &#x3C;=&#x3E; Food &#x3C;=&#x3E; The Land &#x3C;=&#x3E; Tech`

post title truncates

---

api/graphql/filters.js
api/graphql/makeModels.js
api/graphql/schema.graphql
api/models/Community.js
api/services/Search.js
api/services/Search/forPosts.js
api/services/Search/util.js
migrations/20200617090839_add_community_privacy_settings.js

488 public communities

---

api/models/Notification.js
api/services/Email.js

* Adds email notification for Announcement
* New email template in SendWithUs at https://app.sendwithus.com/#/edit/u/tem_xMGgjc4cfHCYDr8gWRKwhdXF/en-US/ver_dx7C8JVDGp3HTrJXyY8fSRw3
* NOTE: Tests are out of date on hylo-node

Adds email notification for Announcements

---

api/models/post/validatePostData.js

Remove location requirement for resource type posts

---

api/graphql/index.js
api/graphql/makeModels.js
api/graphql/mutations/index.js
api/graphql/mutations/join_request.js
api/graphql/schema.graphql
api/models/Activity.js
api/models/JoinRequest.js
migrations/20200707214505_add_join_requests_status.js

Community join requests

---

CHANGELOG.md
api/graphql/filters.js
api/models/Post.js

Fixes https://github.com/Hylozoic/hylo-node/issues/529

Anyone can see comments on public posts

---

CHANGELOG.md
api/graphql/makeModels.js
api/models/Post.js

We don't need to do that anymore. This eliminates many many queries!

Stop looking up a post's type in its tags

---

api/controllers/SessionController.js
package.json
yarn.lock

Required with deploy of: https://github.com/Hylozoic/hylo-evo/pull/651

Upgrades Google OAuth to current, fixes hylo-evo#646

---

api/graphql/schema.graphql
api/services/InvitationService.js

Fixes: https://github.com/Hylozoic/hylo-node/issues/564

Fix community invite page

---

cron.js

Hopefully fixes https://github.com/Hylozoic/hylo-node/issues/559
I suspect this is new from the backend updates though and might not solve Mike's lack of digests?

Fix bug in sending daily digests

---

api/graphql/index.js
api/graphql/makeModels.js
api/graphql/mutations/index.js
api/graphql/mutations/index.test.js
api/graphql/schema.graphql
api/models/Skill.js
api/models/User.js
migrations/202011152160014_add-skills-to-learn.js
migrations/schema.sql

Don't really love this solution, but after many attempts this was the easiest/best way i could come up with
Fixes https://github.com/Hylozoic/hylo-node/issues/556

Skills to learn

---

CHANGELOG.md
api/graphql/makeModels.js
api/graphql/schema.graphql
api/models/User.js

Add query for a person's upcoming events

---

CHANGELOG.md
api/graphql/index.js
api/graphql/makeModels.js
api/graphql/mutations/affiliation.js
api/graphql/mutations/index.js
api/graphql/schema.graphql
api/models/Affiliation.js
api/models/User.js
migrations/20201209185344_add-user-affiliations.js

Closes #548 
Related: https://github.com/Hylozoic/hylo-evo/pull/723

548 custom org affiliations

---

api/graphql/mutations/affiliation.js

Small update to `createAffiliation` to only validate populated urls

update url validation when creating a user affiliation

---

api/graphql/makeModels.js
api/graphql/schema.graphql

Also add person resolver to memberships to fix some bugs on the front-end
Fixes https://github.com/Hylozoic/hylo-node/issues/596

Fix issue where people are seen incorrectly as a moderator

---

api/graphql/filters.js
api/graphql/index.js
api/graphql/makeModels.js
api/graphql/schema.graphql
api/models/Group.js
api/services/Search.js
api/services/Search/forPosts.js
lib/graphql-bookshelf-bridge/fetcher.js

Ensure we show the right set of posts and groups for each context (public, all and group)

590 correct posts for context

---

CHANGELOG.md
api/graphql/makeModels.js
api/graphql/schema.graphql
api/services/Search/forPosts.js
api/services/Search/util.js
lib/graphql-bookshelf-bridge/makeResolvers.js

Replacing isFuture
Fixes https://github.com/Hylozoic/hylo-node/issues/649
Needed for https://github.com/Hylozoic/hylo-evo/issues/907

Filter posts by afterTime and beforeTime

---

api/graphql/index.js
api/graphql/mutations/index.js
api/graphql/mutations/user.js
api/graphql/schema.graphql
api/models/User.js
migrations/20211118103939_add_deleted_user_record.js
test/unit/models/User.test.js

Node 620 delete user (includes prior deactivate user commits)

---

api/graphql/index.js
api/graphql/mutations/index.js
api/graphql/mutations/user.js
api/graphql/schema.graphql
api/models/User.js
test/unit/models/User.test.js

What else does this need to work? This would be my first mutation, so curious to know if I have missed anything.
For #620

Node 620 deactivate user

---

api/controllers/SessionController.js
api/models/LinkedAccount.js
api/models/User.js
api/services/UserSession.js

Addresses the issue of how to handle reactivation in the backend.
Closes #620

Automatically reactivate user if they log back in

---

api/models/Media.js
api/models/User.js
lib/uploader/storage.js
test/unit/models/Media.test.js

Switch to wiping user records, instead of deleting them

---

.env.example
README.md
api/controllers/SessionController.js
api/controllers/UserController.js
api/graphql/index.test.js
api/models/LinkedAccount.js
api/models/User.js
api/models/UserVerificationCode.js
api/policies/checkJWT.js
api/policies/isAdmin.js
api/services/Email.js
api/services/Frontend.js
config/passport.js
config/policies.js
config/routes.js
migrations/20211028160014_verify_email_codes.js
migrations/schema.sql
package.json
test/setup/factories.js
test/unit/controllers/SessionController.test.js
test/unit/controllers/UserController.test.js
yarn.lock

Add user_verification_codes table
Add JWT based auth, and using that for password resetting and email verify links

Add backend and APIs for verifying an email address

---

api/models/event/mixin.js

Add UTC to end of pretty ranges, for email purposes

---

api/services/Search/util.js
api/services/Search/util.test.js
test/unit/services/Search.test.js

Closes #700 
This was partially already addressed in another PR to close #701 so this is just a baby one

Add location to group query fields

---

api/graphql/makeModels.js
api/graphql/schema.graphql
api/services/Search.js

Add group type as a filter for group search

---

CHANGELOG.md
api/models/Group.js
api/models/User.js
cron.js

And once again return num_members for the memberCount attribute for groups for performance.
Fixes https://github.com/Hylozoic/hylo-node/issues/741

Update group num_members in cron job

---

api/graphql/makeModels.js
api/graphql/schema.graphql
api/models/Group.js
api/models/Location.js
migrations/20220323135403_add-geo-shape-to-groups.js

Closes https://github.com/Hylozoic/hylo-node/issues/729

Add geo_shape column to groups

---

CHANGELOG.md
api/models/Group.js

Fixes https://github.com/Hylozoic/hylo-node/issues/765

Fix issue where notifications are turned off for creator of group

---

api/graphql/schema.graphql
api/services/Search.js

Node 767 hide extension data on flag

---

api/graphql/makeModels.js
api/graphql/schema.graphql
migrations/20220424135403_add-descriptors-to-groups.js

Fixes https://github.com/Hylozoic/hylo-node/issues/670

Add moderator and type descriptor fields to groups

---

api/services/Search.js
seeds/dummy/dummy.js
seeds/farm-dev/add-farm-groups.js

Fix farm filter code and updated seed data

---

APIs.md
api/controllers/UserController.js
api/graphql/index.js
api/graphql/mutations/group.js
api/graphql/mutations/index.js
api/graphql/schema.graphql
api/models/User.js

Add role parameter to createUser api call

---

api/controllers/ExportController.js

Fixes: https://github.com/Hylozoic/hylo-node/issues/816

Add user id to member export CSV

---

api/models/Group.js
api/models/GroupExtension.js

Add groupExtenions to group update

---

lib/constants.js

Fixed collab options and linting in constants.js

---

api/graphql/makeModels.js
api/graphql/mutations/group.js
api/graphql/schema.graphql
api/models/CustomView.js
api/models/CustomViewTopic.js
api/models/Group.js
api/services/Search/util.js
migrations/20211118103939_add_deleted_user_record.js
migrations/20220623155959_custom_view_for_groups.js
package.json

Node 828 custom views

---

api/graphql/makeModels.js
api/graphql/schema.graphql
api/models/post/setupPostAttrs.js
migrations/20220720131223_add_extra_project_fields_to_posts.js
migrations/schema.sql

Node 837 add fields to posts for projects

---

api/graphql/makeModels.js
api/graphql/schema.graphql
api/models/CustomView.js
api/models/CustomViewTopic.js
api/models/Group.js
api/models/mixins/HasSettings.js

Add topic filtering to custom views
Support multiple custom views for a group

Additional changes to get custom views fully working

---

api/graphql/index.js
api/graphql/makeModels.js
api/graphql/mutations/collection.js
api/graphql/mutations/index.js
api/graphql/schema.graphql
api/models/Collection.js
api/models/CollectionsPost.js
api/models/CustomView.js
api/models/Group.js
api/models/Post.js
api/services/Search/util.js
migrations/20220922155959_post-collections.js
package.json

Connected to CustomViews
Fixes https://github.com/Hylozoic/hylo-node/issues/861

Add support for post Collections

---

api/models/Group.js
migrations/schema.sql
test/unit/models/GroupExtension.test.js

Add default general topic to all new groups

---

api/models/Group.js

Pick settings on group creation

---

api/models/FlaggedItem.js
api/models/Notification.js
api/models/comment/notifications.js
api/services/Frontend.js
test/unit/models/FlaggedItem.test.js

closes #883 
I want to test this in staging

Update comment url for notifications

---

api/graphql/filters.js
api/graphql/schema.graphql

For https://github.com/Hylozoic/hylo-evo/issues/1331

Evo 1331 child posts

---

api/graphql/makeModels.js
api/graphql/schema.graphql
api/services/Search/forPosts.js

Added more query params to postQuery to allow My Home functionality

---

lib/constants.js

For https://github.com/Hylozoic/hylo-evo/issues/1417

Update product categories

---

api/models/Notification.js
api/services/Frontend.js

Most of the comment notification changes had already been made, and the one remaining one is for mobile notifications. I can't test those directly in my local dev however...
Closes #907

Add full comment url to comment notifications

---

api/graphql/makeModels.js
api/models/Comment.js
api/models/Post.js
api/services/RichText.js
test/unit/services/RichText.test.js

Required for: https://github.com/Hylozoic/hylo-evo/issues/1308

Adds extra CSS class for mentioned current user

---

api/graphql/index.js
api/graphql/mutations/zapier.js
api/graphql/schema.graphql
api/models/FlaggedItem.js
api/models/Group.js
api/models/Post.js
api/models/User.js
api/models/ZapierTrigger.js
api/models/ZapierTriggerGroup.js
api/models/post/createPost.js
api/services/Frontend.js
migrations/20230221155959_zapier-triggers-multiple-groups.js
package.json

Switch zapier triggers to work on multiple groups at the same time
Also get Post Creation trigger working! 
And add more date like group URLs and profile URLs to the data sent for triggers

826 zapier integration

---

api/graphql/schema.graphql
lib/constants.js

https://github.com/Hylozoic/hylo-evo/issues/1462

Minor farm list updates

---

api/graphql/filters.js
api/graphql/index.js
api/graphql/mutations/index.js
api/models/Group.js
api/models/Post.js
api/services/Search/util.js
config/env/production.js
lib/mixpanel.js

Fixes https://github.com/Hylozoic/hylo-evo/issues/1479
Also some other small things

Only show pinned posts from current (parent) group, not child groups

---

api/graphql/makeModels.js
api/graphql/mutations/index.js
api/graphql/schema.graphql
api/models/Comment.js
api/models/Post.js
test/unit/models/Post.test.js

Also clean up and test reactions code more
Fixes https://github.com/Hylozoic/hylo-node/issues/931

Make sure you can't double vote from mobile app

---

CHANGELOG.md
api/controllers/UserController.js
api/models/User.js
api/services/Frontend.js
config/policies.js
config/routes.js
lib/HyloJWT.js
lib/group/digest2/personalizeData.js
test/unit/models/Media.test.js
test/unit/services/digest2.test.js

Allow for fetching and updating notification settings via JWT
Use said JWT in change notification settings URL in digest emails
Fixes https://github.com/Hylozoic/hylo-node/issues/958

958-update-notifications-from-token

---

README.md
api/graphql/makeModels.js
api/graphql/schema.graphql
api/models/Group.js
api/models/Media.js
migrations/20230907216001_add-purpose-to-groups.js

Add group purpose field 
Also do some updates to the linting and README

963 group purpose

---

api/models/Notification.js
api/models/Post.js
api/services/Frontend.js

For https://github.com/Hylozoic/HyloReactNative/issues/663

Add chat urls to notifications

---

api/graphql/makeModels.js
api/graphql/schema.graphql
api/models/Post.js
api/models/post/setupPostAttrs.js
migrations/20240610131324_proposalType-to-votingMethod.js
migrations/schema.sql

Node 969 proposal final

---

api/models/Post.js
package.json
yarn.lock

Flagged as an evo ticket but better fixed in node

Escape proposal option inputs
