api/controllers/CommunityController.js, api/controllers/SessionController.js, api/controllers/UserController.js, config/policies.js, config/routes.js
Not backwards-compatible; must be deployed with https://github.com/Hylozoic/hylo-frontend/pull/46 because it removes `req.session.invitationCode`
=> Signup without code

seeds/tags.js
This is for the sake of new developers who use the README.md to set up their database, and then may get curious about how come 'intention' isn't in the default topics
=> intention should also be in seeds file

api/services/Websockets.js, package.json
figured this out by switching `sails.config.sockets.adapter` to `memory` and it worked fine. then reading a bunch of the source code to do with socket.io-redis
=> socket.io-redis 0.1.4 not up to date enough to work

api/controllers/InvitationController.js
this trello card: https://trello.com/c/JOSC6Ivn/121-inviting-people-to-dev-topic-on-hylo-via-hylo-user-names-throws-both-success-and-error-state-at-same-time
=> don't treat empty string as an email list, fixes 'invite to tag' process

api/services/Search.js, test/unit/services/Search.test.js
Turns out the existing PG full text search term search is configured to do exactly this, so I went ahead and used just that.
=> Add last name to autocomplete search

api/graphql/fetcher.js, api/graphql/models.js, api/graphql/schema.graphql, api/graphql/util/applyPagination.js
So I was looking into the pagination bug for direct message threads, and started considering rewriting that code to use GraphQL, which uncovered the fact that I hadn't yet implemented a key part of pagination: getting the total number of results for a given query, so the client knows whether it's at the end of the result set yet.
The total number of results is not straightforward to add to the API as it currently is, because it's a property of the whole set of results, not any one instance.
The way this is handled by Relay is to add another level of indirection: instead of
```graphql
me {
memberships(first: 3) {
community {
name
}
}
}
```
you might have
```graphql
me {
memberships(first: 3) {
edges {
node {
name
}
pageInfo {
hasNextPage
}
}
}
```
(see the [spec …
=> add total counts for pagination to our graphql api

api/models/Post.js
this was because previously the comment count got incremented before the websockets notification was sent,
and in the refactor done at that time it was moved to after the websocket event, which is why we now
check 'num_comments' for a 0 value instead of a 1
https://github.com/Hylozoic/hylo-node/blob/761a8ee7537990ef448087490bdf84ecd15d20ff/api/models/comment/createAndPresentComment.js
=> pushing new threads over websockets fix

api/models/Post.js
there's no need, as far as I can tell, for this parent_post_id to be sent down. I've taken it out not because it was technically a bug on the backend as on the frontend, but because the fix on the frontend makes passing it extraneous
goes with https://github.com/Hylozoic/hylo-redux/pull/292
=> fix realtime comments for posts

api/models/comment/createAndPresentComment.js
with recent not being set to true immediately, fetching of threads based on websockets doesn't have up to date data
=> make sure that new comment is set to be recent

api/graphql/index.js, api/graphql/makeModels.js, api/graphql/schema.graphql, api/models/User.js, lib/graphql-bookshelf-bridge/fetcher.js, lib/graphql-bookshelf-bridge/makeResolvers.js, lib/graphql-bookshelf-bridge/util/initDataLoaders.js, test/api/graphql/index.test.js
This PR extends the graphql-bookshelf bridge to allow multiple different GraphQL types to be backed by the same Bookshelf models.
It also uses this to add MessageThread and Message to the GraphQL schema, which are backed by Bookshelf models Post and Comment respectively.
The syntax for model specs (the output of `makeModels`) changes to support this in a few ways, all of which can be seen in the diffs. Overall, the purpose of these changes is for disambiguation: if multiple GraphQL types point to the same Bookshelf model, at the time when we have a Bookshelf model and need to map it back to a GraphQL type, we need to know which one to map it back to.
1. The top-level keys are now GraphQL schema type names, not database table names.
2. The syntax for aliases in `relations` changes:
```js …
```
=> allow different GraphQL schema types to point to the same table

api/graphql/makeModels.js, api/graphql/schema.graphql
Yet another addition! This one is to grab the post for a comment so we can display its name (and link to its id) in a comment card on the member profile overview.
=> Get parent post from comment

api/graphql/makeModels.js, api/graphql/schema.graphql, api/models/Community.js, api/models/CommunityTag.js, api/models/Tag.js, test/unit/models/Tag.test.js
so this PR makes it so that if you're interested in the TOTAL number of posts for a topic, look at the Topic itself, and grab `postsTotal` off it, but if you're interested in the total number of posts for a topic within a community, grab it off of the CommunityTopic using `postsTotal`
=> add community topics

migrations/scripts/updateMigrationsTable.js, package.json
Obtain a directory listing of `./migrations`, and remove everything in `knex_migrations` which isn't one of those files. To run: `npm run update-migrations`.
This is to address the situation where an existing developer has a couple of hundred migrations in their database, and we have removed all but the 2017 migrations from the directory. Knex will complain if any files are missing from `knex_migrations`.
=> Equalises knex_migrations with directory

api/services/FullTextSearch.js, migrations/20170519141924_tags-id-biginteger.js, migrations/schema.sql
This was a fiddly little thing. In order for it to work, I needed to provide the knex object used in migrations (which is normally set up to use a transaction for each migration I believe) to the view create/drop functions in FullTextSearch. They will use the old `bookshelf.knex` at other times.
Took me quite a long time to realise I couldn't do 
```
.then(FullTextSearch(createView(null, knex)))
```
instead of 
```
.then(() => FullTextSearch(createView(null, knex)))
```
Oh well, live and learn :grinning:
=> Make tags.id bigint

api/models/comment/createAndPresentComment.js, api/models/post/findOrCreateThread.js, api/models/post/findOrCreateThread.test.js, api/services/Websockets.js, test/unit/models/comment/createAndPresentComment.test.js
this would happen when using hylo-redux... opening the modal to start a new thread, then trying to send a comment. the user feedback for it not working wasn't good/implemented
related to the calling of createAndPresentComment (at comment creation)
related to the calling of findOrCreateThread
=> first time use of findOrCreateThread would break, and so would first comment

api/models/User.js
https://trello.com/c/ZWvyEYuK/463-evo-cannot-change-name-from-settings-page
=> fixes issue where saving settings throws an error

api/services/Search/forUsers.js
```
query ($slug: String, $first: Int, $sortBy: String, $offset: Int, $search: String) {
network (slug: $slug) {
id
name
avatarUrl
memberCount
members (first: $first, sortBy: $sortBy, offset: $offset, search: $search) {
items {
id
name
avatarUrl
location
tagline
}
hasMore
}
}
}
{
"slug": "impact-hub-global",
"first": 5,
"search": "juggling"
}
```
currently this query breaks with 
`table name \"skills_users\" specified more than once`
=> (wip) update Search.forUsers to work with skills

cron.js, worker.js
@richchurcher I went through and tested this thoroughly and stacktraces appear to be spitting out correctly in all cases now.  I also added the jobId to the rollbar handling.  was there anything else you were thinking about in for this issue: https://hylozoic.atlassian.net/browse/WEB-35?
=> Web 35 worker error stacktraces

api/models/Notification.js
I've been hitting my head against a brick wall trying to understand the interaction between Sails, Kue, Heroku, and Redis. I still don't feel I understand what's happening, or how to debug the problem. In the interim, to stop blocking us on this issue, I'd like to try putting a bit more logging in and see what happens when it's live for a few days. Perhaps if I stop thinking about it for awhile the answer will emerge!
=> WEB-35: Provide more debugging context on Redis errors

api/graphql/mutations/index.js, api/graphql/schema.graphql, api/models/FlaggedItem.js, api/services/Frontend.js, test/unit/graphql/mutations/mutations.test.js, test/unit/models/FlaggedItem.test.js
This changes the logic of the flagInappropriateContent logic so that links are generated on the backend instead of passing the link from the frontend (ie: mobile or web).
The PR for the frontend is here: https://github.com/Hylozoic/HyloReactNative/pull/67
(though it's not finished yet).
=> MBL-17 update logic for flagging content mutations to generate links on backend

api/models/Notification.js, api/models/Post.js, api/models/post/createPost.js, api/models/post/createPost.test.js, api/models/util/relations.js, api/models/util/relations.test.js, migrations/20171014111135_link-preview-id-bigint.js
=> MBL-81: set backend up to deliver socket updates in correct format 

api/services/Slack.js
They didn't used to so I'm not sure when it changed.
=> quotes looked like &quot; in slack messages

api/graphql/index.js, api/graphql/mutations/index.js, api/graphql/mutations/network.js, api/graphql/mutations/network.test.js, api/graphql/schema.graphql
=> Web 330/network settings mutations

api/controllers/MobileAppController.js, test/unit/controllers/MobileAppController.test.js
This is a pretty trivial one. Currently the request will return `undefined` for the most part (if a user has the correct version). Even though the status code is correct, the fact that we're returning an empty body for an `application/json` request is technically an error because empty string is not, as it turns out, valid JSON :laughing: so there has been a swallowed error on startup for a long time.
Once I started logging it it took me quite a while to realise that it wasn't the source of our problems with the dev environment, but we should still fix it. Swallowed errors ain't cool.
Note: the client code ignores the body unless it has an error property, so this doesn't break anything.
=> Fix versioncheck

api/models/Comment.js
Fixes issue with creating new comments. The `Post.communities` relationship was not loaded in the new Comment context. Now forced loaded and no longer breaks.
=> Await for relation to load before calling community in activity

api/services/Search/util.js
Required by https://github.com/Hylozoic/hylo-evo/pull/684
=> Add post.created_at sort option to posts search

seeds/migrations.js
Hello there :wave: 
while, trying to run the project locally encountered the following error:
```
(base) ➜  hylo-node git:(dev) ./node_modules/.bin/knex seed:run
Using environment: development
Error: Error while executing "/home/vesko/Workspace/hylo-node/seeds/migrations.js" seed: Cannot read property 'reduce' of undefined
at Seeder._waterfallBatch (/home/vesko/Workspace/hylo-node/node_modules/knex/lib/seed/Seeder.js:146:23)
TypeError: Cannot read property 'reduce' of undefined
at addMigrations (/home/vesko/Workspace/hylo-node/seeds/migrations.js:15:18)
at /home/vesko/Workspace/hylo-node/seeds/migrations.js:8:14
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Seeder._waterfallBatch (/home/vesko/Workspace/hylo-node/node_modules/knex/lib/seed/Seeder.js:143:9) …
```
=> Fix db seeding

.devcontainer/README.md, .devcontainer/db-seed/Dockerfile, .devcontainer/db-seed/init-db.sh, .devcontainer/docker-compose.seed.yml
Update to #578 that allows DB initialisation commands to be executed by developers opting not to install Postgres tooling locally. May also avoid some potential issues with the existing setup script- unsure if `db` and `localhost` both resolve to the correct server in the VSCode dev env; but this addition makes such a concern explicit.
=> Docker env seeding

lib/uploader/converter.js, package.json, yarn.lock
This is required for mobile camera photos uploads (https://github.com/Hylozoic/HyloReactNative/issues/409) to be rotated correctly. Currently the same is being handled on the front-end on Web by a FileStack transform. I've tested locally with this setting on the backend and it doesn't change Web behavior, but likely the FileStack transform can be turned off here:
https://github.com/Hylozoic/hylo-evo/blob/fe381649e4d5492457ebee7b60e6c3f9f8f98ab0/src/client/filestack.js#L74
...changing it simply to `? 'https://cdn.filestackcontent.com/' + file.handle`. That is assuming however that we have FileStack setup to pass the EXIF data intact to our backend converter. TBD. 
As is, not changing anything seems retain the current behavior on Web.
=> Handle image rotation contained in EXIF data

api/models/User.js
Fixes: https://github.com/Hylozoic/hylo-evo/issues/748 and https://github.com/Hylozoic/hylo-node/issues/585
=> Correctly return message thread id for a pair and current user

api/graphql/makeModels.js, migrations/20220505135403_remove-default-descriptors-from-groups.js, package.json, yarn.lock
Default is now null and when null we use default text that is easier to translate, instead of storing default "Moderator" or "Group" in the database
Also for type descriptor if that is null then check if type is set and use that if it is, otherwise use Group.
=> Slight tweaks to how custom group moderator and type descriptors work

api/controllers/CommentController.js, api/models/Comment.js, api/services/InvitationService.js, package.json, yarn.lock
Updates to maintain current `Hylo-shared` markdown behavior turning off the autolinking that is now on by default. It may be fine to have it on in these cases, but they were untested so turning it off to maintain previously default behavior here. 
Relates to https://github.com/Hylozoic/hylo-evo/pull/1345 and should not change behavior here.
=> Updates Hylo-shared

api/controllers/PostController.js, api/graphql/filters.js, api/models/Group.js, api/models/post/createPost.js, api/models/post/setupPostAttrs.js, migrations/20221110125837_show-in-public-flag-to-groups.js, migrations/schema.sql
When off then people are not allowed to create public posts from that group. Meaning a post that is chosen to be public must also be posted in at least one group that has allow_in_public set to true.
Fixes https://github.com/Hylozoic/hylo-node/issues/889
=> Add allow_in_public column to groups

api/models/Group.js, api/models/Invitation.js, api/models/User.js, api/services/Analytics.js, config/session.js, package.json, seeds/farm-demo/demo-farms.js, seeds/farm-dev/add-farm-groups.js, yarn.lock
We decided to let all new groups back into the public context, for now. 
And this upgrades old deprecated node-uuid package to newer uuid as a shot in the dark hope that the reason a couple folks have gotten logged in as others is due to duplicate uuid sessions being generated? Also probably good for security to not be using deprecated packages
=> Fixing public groups and hopefully sessions

api/models/Activity.js, api/models/FlaggedItem.js, api/models/Notification.js, api/models/PushNotification.js, api/models/comment/notifications.js, api/services/Frontend.js, api/services/Slack.js, cron.js, lib/group/digest2/savedSearches.js, test/unit/models/Comment.test.js, test/unit/models/FlaggedItem.test.js, test/unit/models/Notification.test.js
Posts without titles
But also when clicking on notification jump to the chat post in the associated chat room
Also comment digest emails now link to the new comment, and in the context of the first group the post is in instead of /all
Fixes https://github.com/Hylozoic/hylo-node/issues/910 and more
=> Make sure all notifications work with chat posts and comments

CHANGELOG.md, api/graphql/makeModels.js, api/graphql/schema.graphql, api/models/Post.js, api/models/post/setupPostAttrs.js, lib/group/digest2/formatData.js, lib/group/digest2/savedSearches.js, migrations/20230808216001_add-timezone-to-posts.js, package.json, test/unit/models/Media.test.js, test/unit/services/digest2.test.js, yarn.lock
Show correct timezone for events in emails
For now this always shows the timezone set by/when the person created the event as the event's timezone, and displays that in the email.
Fixes https://github.com/Hylozoic/hylo-node/issues/939
=> 939 timezone in emails

api/models/Group.js, api/models/Notification.js, api/models/Post.js, api/models/ZapierTrigger.js, api/models/comment/notifications.js, api/models/event/mixin.js, api/models/project/mixin.js, api/services/Search/forPosts.js, lib/group/digest2/index.js
- Turn off allow in public for new groups by default
- Fix null post time for notification emails for posts that dont have a start time
- Don't sort pinned posts first when getting posts for chat rooms
- Improve performance by loading eventInvites only for events and post members only for projects
- For post zapier triggers set URL to be post in URL in the first group instead of in the "all" groups context
- Cleanup
=> Odds and ends

migrations/20240218134105_proposals.js, migrations/20240721183827_restore-proposal-option-constraint.js, migrations/dump_schema.sh, migrations/schema.sql, package.json
Fixes #1002 
Two commits:
- fix the migration so that hopefully it won't break any dev machines current or future
- revise yarn script so it can dump a schema that runs under test and dev
I ran hylo-node tests and they worked after running `yarn dump`
I dropped my dev db and ran the READ.ME commands:
- createdb...
- cat schema...
- yarn knex seed:run
and I was able to run, create an account, creat a group, and create a proposal. Yippee!
=> Node 1002 fix migrations and schema dump

api/graphql/mutations/post.js, api/models/Post.js
Fixes #1001 
Existing pattern for Bookshelf arguments was inadvertently used when knex object is referenced.
Note:
The `opts.transacting ||= { transacting: false }` lines are a hack to tell knex when there are not transactions. This appears to only be the case in tests. This line is therefore necessary for tests that do not wrap database accesses in transactions. A proper fix would be to wrap tests in transactions, but that's more work than may be necessary.
Main disadvantage is reliance on `knex#transacting` not changing and breaking this. If that happens, it should only affect tests and not production.
=> Node 1001 Correct transacting arguments, tests passing
